[package]
name = "iced_style"
description = "The default set of styles of Iced"
version = "0.12.3"
edition = "2021"

[dependencies]
iced_core.version = "0.12"
iced_core.features = ["palette"]

palette.workspace = true
once_cell.workspace = true
